### ISSUE TITLE
Keyboard event not persisted after updating from version 0.2.1?

### ISSUE THREAD

**Issue by kyrasteen** [glenjamin/react-hotkey#10]
Hey thanks for the handy mixin!

I just updated the version (long overdue) from 0.2.1 to the most recent version.

It seems like with the older version the keyboard event was being persisted, and I could access `event.target` in a callback. Now with the update, where I previously referenced `event.target` it is undefined. Switching back to version 0.2.1 eliminates the js error I am seeing 'Cannot read property tagName of undefined` - code referenced below -  listening for the default keyup event

    handleHotKey: function (ev) {
      var tag = ev.target.tagName.toLowerCase();
      if (tag === 'textarea' || tag === 'input' || !this.state.allowKeypress) { return; }
      this.emit('hotKeyPress', ev);
    }

Any thoughts would be appreciated :)
Thanks

**Comment by glenjamin** [comment]
This sounds like it's related to react's event pooling.

I had a look through the history, and there's been not changes to how we interact with the pooling system.

This lib has never persisted events for you, but it does allow you to use `event.persist()` if you need it.

All I can suggest is try calling `.persist()` at the start of your event handler, or use the debugger to trace what's going on.

**Comment by kyrasteen** [comment]
Thanks for the advice, I did try calling `.persist()` at the start of my event handler, but the event target remained undefined. Something else must be going on, I will dig in more with the debugger.
