### ISSUE TITLE
Compatibility with React 15.4

### ISSUE THREAD

**Issue by mjomble** [glenjamin/react-hotkey#11]
This line in index.js fails with React 15.4.0:

```javascript
var SyntheticKeyboardEvent = require('react/lib/SyntheticKeyboardEvent');
```

From the [React 15.4.0 blog post](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html):

> **If you only use the official and documented React APIs you won't need to change anything in your application.**
> However, there is a possibility that you imported private APIs from `react/lib/*`, or that a package you rely on might use them. We would like to remind you that this was never supported, and that your apps should not rely on internal APIs. The React internals will keep changing as we work to make React better.

**Comment by glenjamin** [comment]
I'm not actively using this module at the moment, so unlikely to have time to delve into this.

I'll happily take a PR though.

One of the original goals with this lib was to get a React-wrapped event object rather than the standard browser event object - which is why I had to reach into the internals. This might not be as important these days.

**Comment by hotohoto** [comment]
+1

**Comment by hotohoto** [comment]
What is the reason why my PR have been failed?

https://travis-ci.org/glenjamin/react-hotkey/builds/176617307

**Comment by glenjamin** [comment]
Should be resolved in 0.7.0

**Comment by mjomble** [comment]
This will do as a quick fix, but there is absolutely no guarantee that a future change to React internals won't unexpectedly break it again.

It might be a good idea to look into a more permanent solution or at least update the README to inform users of this library that it relies on an unstable technique and may unexpectedly break builds.

I can provide a PR for the README if needed.

**Comment by glenjamin** [comment]
PR for the readme to warn about internals usage sounds good.

React doesn't expose the synthetic events as a supported API, so there's no better way to get the same effect. See https://github.com/facebook/react/issues/285 for more details about this.

I have some vague ideas about a different way to approach hotkeys, using a child component and mousetrap, but nothing I'm likely to work on or publish any time soon.
