### ISSUE TITLE
Make React a peer dependency

### ISSUE THREAD

**Issue by aldendaniels** [glenjamin/react-hotkey#3]
This would avoid the risk of bundling multiple copies of React for Browserify users.

**Comment by glenjamin** [comment]
Oh, I'm not really sure why I didn't.

I'll sort this out today.

**Comment by glenjamin** [comment]
Published as v0.3.0 d573d3d

**Comment by aldendaniels** [comment]
Thanks! Just curious - is there a reason you didn't declare React as an [NPM Peer Dependency](http://blog.nodejs.org/2013/02/07/peer-dependencies/)? This would show validation if React wasn't available.

**Comment by glenjamin** [comment]
Two reasons:

There's a bunch of problems with peerDeps, and they're slated for deprecation https://github.com/npm/npm/issues/6565 https://github.com/npm/npm/issues/5080

Also, it means I don't need to cut a new version every time react is upgraded.

**Comment by aldendaniels** [comment]
Sure enough. It's a pity, since peer dependencies served a valid use case. Hopefully NPM will design a successor to meet the same need.

**Comment by aldendaniels** [comment]
@glenjamin - for the record - it looks like peer dependencies aren't being deprecated after-all. Instead, they're being simplified in NPM v3. See @othiym23 comment in https://github.com/npm/npm/issues/6565.

**Comment by aldendaniels** [comment]
Also, as to your second point:

 > Also, it means I don't need to cut a new version every time react is upgraded.

That's easy. You can just us the semserver `>=` syntax to accept all new versions of React.

**Comment by rk08** [comment]
@aldendaniels I have a react app, in which folder name is sports, inside the sports folder I have node modules, inside the node modules folder I have football folder and react folder.
If go to football folder and do npm install react its installing react, which makes my application fail, how to prevent this command npm install react from being successful.
Is it anyway we can right a script to prevent this process to happen, but it should work when we do npm install react in sports folder. Is there any already npm packages which we use it make automatically validated our npm commands.
