### ISSUE TITLE
react-hotkey doesn't work

### ISSUE THREAD

**Issue by iambusybox** [glenjamin/react-hotkey#4]
I'm trying to use a mixin you made - react-hotkey - but it doesn't work in my project.

....
var hotkey = require('react-hotkey').activate();

var LoginBody = React.createClass({
  mixins: [ReactRouter.State, ReactRouter.Navigation, hotkey.Mixin('handleHotkey')],

  handleHotkey: function(e) {
        // receives a React Keyboard Event
        // http://facebook.github.io/react/docs/events.html#keyboard-events
        alert('key = ' + e.keyCode);
  },
...

Once I've started the application I've got an exception:

D:\Smart\node_modules\react-hotkey\index.js:13
        documentListener = EventListener.listen(document, event, handle);
                                                ^
ReferenceError: document is not defined
    at Object.exports.activate (D:\Smart\node_modules\react-hotkey\index.js:13:49)
    at D:\Smart\node_modules\jsx-loader\index.js?harmony!D:\Smart\src\jsx\smart\routes\login.jsx:6:38
    at NormalModuleMixin.Module._compile (D:\Smart\node_modules\enhanced-require\lib\Module.js:53:18)
    at RequireContext.theRequire (D:\Smart\node_modules\enhanced-require\lib\RequireContext.js:169:10)
    at D:\Smart\node_modules\jsx-loader\index.js?harmony!D:\Smart\src\jsx\smart\routes.jsx:11:21
    at NormalModuleMixin.Module._compile (D:\Smart\node_modules\enhanced-require\lib\Module.js:53:18)
    at RequireContext.theRequire (D:\Smart\node_modules\enhanced-require\lib\RequireContext.js:169:10)
    at D:\Smart\node_modules\jsx-loader\index.js?harmony!D:\Smart\server.jsx:36:14
    at NormalModuleMixin.Module._compile (D:\Smart\node_modules\enhanced-require\lib\Module.js:53:18)
    at RequireContext.theRequire (D:\Smart\node_modules\enhanced-require\lib\RequireContext.js:169:10)

React version is 0.12.2

What I'm doing wrong?

By the way, the following code works very well:

...
componentDidMount: function() {    
    $(document.body).on('keydown', this.handleKeyDown);
  },
  componentWillUnmount: function() {
    $(document.body).off('keydown', this.handleKeyDown);
  },

handleKeyDown: function(e) {
    alert('key = ' + e.keyCode);
  },

But I would like to use your mixin.

Thank you in advance for any response.

**Comment by glenjamin** [comment]
I think this will be down to server side rendering.

Try only calling activate() in componentDidMount of the root component - or some other way to only run activate on the client side.

**Comment by iambusybox** [comment]
I did. There was no exception but method handleHotkey was not even invoked when a key is pressed on a keyboard.

**Comment by glenjamin** [comment]
It sounds like activate isn't being called at all anymore in that case.

Could you try running the example from the repo, does that work?

If so, I'd need to see more code - ideally a reproducible test-case to help more.
